version: "3.8"

services:
  postgres:
    image: postgres:13.2-alpine
    restart: always
    container_name: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: docker
      POSTGRES_PASSWORD: docker
      POSTGRES_DB: squate
  adminer:
    image: adminer
    container_name: adminer
    restart: always
    ports:
      - 8000:8080
